name: Trigger and Monitor Workflow

on:
  workflow_call:
    inputs:
      owner:
        description: 'GitHub Owner or Organization'
        required: true
        type: string
      repository:
        description: 'Repository Name'
        required: true
        type: string
      event_type:
        description: 'Event Type to trigger'
        required: true
        type: string
      max_time:
        description: 'max execution time'
        required: false
        default: 1200
        type: string
      wait_time:
        description: 'check status every N secods'
        required: false
        default: 10
        type: string

    outputs:
      workflow_conclusion:
        description: "workflow conclusion"
        value: ${{ jobs.trigger.outputs.workflow_conclusion }}

jobs:
  trigger:
    runs-on: one-thd-gcp 
    env:
      OWNER: ${{ inputs.owner }}
      REPO: ${{ inputs.repository }}
      EVENT_TYPE: ${{ inputs.event_type }}
      TOKEN: ${{ secrets.ECC_V2_PAT }}
      MAX_EXEC_TIME: ${{ inputs.max_time }}
      SLEEP_TIME: ${{ inputs.wait_time }}
      
    outputs:
      workflow_conclusion: ${{ steps.trigger.outputs.workflow_conclusion }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Trigger workflow and wait
        id: trigger
        run: |
          echo "Triggering workflow in repository ${OWNER}/${REPO}..."
          
          MAX_TIME=$(( ${MAX_EXEC_TIME} ))  # Convert to integer in bash
          WAIT_TIME=$(( ${SLEEP_TIME} ))

          # Trigger the repository_dispatch event
          resp=$(curl -X POST -s "https://api.github.com/repos/${OWNER}/${REPO}/dispatches" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${TOKEN}" \
            -d "{\"event_type\": \"${EVENT_TYPE}\"}")
          
          if echo "$resp" | grep -q "message"; then
            echo "Error: ${resp}"
            exit 1
          else
            echo "Workflow triggered successfully"
          fi
          
          # Find the triggered workflow run
          counter=0
          while true; do
            counter=$((counter + 1))
            workflow=$(curl -s "https://api.github.com/repos/${OWNER}/${REPO}/actions/runs?event=repository_dispatch" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${TOKEN}" | jq '.workflow_runs[0]')
          
            if [ -z "$workflow" ]; then
              echo "No workflow runs found. Retrying..."
              sleep 2
              continue
            fi
          
            wtime=$(echo "$workflow" | jq -r '.created_at')
            atime=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            tdif=$(( $(date -d "$atime" +"%s") - $(date -d "$wtime" +"%s") ))
          
            if [ "$tdif" -gt 10 ]; then
              if [ "$counter" -gt 3 ]; then
                echo "Workflow not found after multiple attempts"
                exit 1
              else
                echo "Waiting for workflow to start..."
                sleep 2
              fi
            else
              break
            fi
          done
          
          wfid=$(echo "$workflow" | jq -r '.id')
          conclusion=$(echo "$workflow" | jq -r '.conclusion')
          
          echo "Workflow id is ${wfid}"
          
          # Wait for the workflow to complete
          counter=0
          while [ "$conclusion" = "null" ]; do
            if [ "$counter" -ge "$MAX_TIME" ]; then
              echo "Time limit exceeded"
              exit 1
            fi
            
            echo "Check run on https://github.com/${OWNER}/${REPO}/actions/runs/${wfid}"
            sleep "$WAIT_TIME"
            
            conclusion=$(curl -s "https://api.github.com/repos/${OWNER}/${REPO}/actions/runs/${wfid}" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${TOKEN}" | jq -r '.conclusion')
            counter=$(( counter + "$WAIT_TIME" ))
          done
          
          echo "workflow_conclusion=$conclusion" >> $GITHUB_OUTPUT
          
